### ISSUE TITLE
Certain unicode emoticons/pictograms result in error

### ISSUE THREAD

**Issue by daT4v1s** [Aegisub/Aegisub#121]
- After
  - opening a `.ass` subtitle
  - copy-pasting text into the editor
containing certain unicode pictograms such as:
`🌤🌂🎜👤👥👀😕`

 i get a blank dialog, on closing it, the program is closed as well
`linux` `Aegisub 6962-master-2cb92a5`

![Screenshot from 2019-04-26 18-00-53](https://user-images.githubusercontent.com/47403824/56841289-e59b0d00-685a-11e9-8708-0f55a0c34dab.png)

![Screenshot from 2019-04-26 18-00-45](https://user-images.githubusercontent.com/47403824/56841280-d3b96a00-685a-11e9-9733-e9e2a104c0de.png)

but simpler unicode `☹☺` does not have that problem

**Comment by wangqr** [comment]
Does this happen in all text boxes or the subtitle box only? If this happens in all text boxes, then this might be a wxWidgets issue.

**Comment by daT4v1s** [comment]
some of the other text fields support it
![Screenshot from 2019-04-27 10-26-15](https://user-images.githubusercontent.com/47403824/56850953-56800a80-68d7-11e9-923e-08af8b472847.png)

**Comment by daT4v1s** [comment]
that was vague, more specifically, 
it cant handle Unicode characters outside/higher than 
the [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Basic_Multilingual_Plane), 
therefore `\uFFFD` `�` works, 
but `\u10000` `𐀀` produces error

**Comment by wangqr** [comment]
Can you provide more information about your environment, e.g. which distro are you using? I cannot reproduce this issue on Archlinux.

![image](https://user-images.githubusercontent.com/8182182/58215897-0cb5f480-7cca-11e9-9956-4f965528920b.png)

**Comment by FichteFoll** [comment]
r6962 is pretty old. Maybe the dependencies are as well and this has been fixed since.

**Comment by FichteFoll** [comment]
Update: Can reproduce.

![2019-05-23_14-00-59](https://user-images.githubusercontent.com/931051/58251133-40912880-7d63-11e9-9a83-f8a8c4a0cd17.png)

My build should be from this commit: https://github.com/TypesettingTools/Aegisub/commit/75fc5f38d79ac2a776f6ccc452a8b7b3cd85c397

**Comment by wangqr** [comment]
Are you using a non-UTF-8 locale? (Can be checked via `locale`)

**Comment by FichteFoll** [comment]
I use en_US.UTF-8.

**Comment by wangqr** [comment]
Well I found the way to reproduce @FichteFoll 's issue. Install `wxgtk-common-dev` and `wxgtk3-dev` from AUR (this upgrades wxWidget from 3.0.x to 3.1.x), then rebuild aegisub should fix this.

**Comment by FichteFoll** [comment]
Ah, yes, I only get the console message as well and my UI looks as shown above. No error dialog or crashes.

**Comment by ilko-k** [comment]
Hi, I know this issue and it's present in all builds after r8870. 8870 handle special characters fine, but newer builds don't.

**Comment by wangqr** [comment]
> Hi, I know this issue and it's present in all builds after r8870. 8870 handle special characters fine, but newer builds don't.

r8870: 14a80dbabd9940f5e8cce9dd08b5f3f0bfb1fa94, r8886: 2720d8c0dc071a56e2a7fd28c0e011263947e256. And the [diff](https://github.com/Aegisub/Aegisub/compare/14a80dbabd9940f5e8cce9dd08b5f3f0bfb1fa94...2720d8c0dc071a56e2a7fd28c0e011263947e256).

> try to open the attached .srt file on any build newer than 8870, it will fail even tough the file is encoded in UTF-8.

If I directly open the srt, the U+266c in the last line will be removedd during conversion. I think this is a issue with the charset detection. If add utf-8 BOM to the file, the srt will load correctly without issue. I am using my own build, which is forked from the master branch, with no modification related to Unicode rendering. Can you provide the disto, and the version of GTK3 and wxWidgets you are using?
![Screenshot](https://user-images.githubusercontent.com/8182182/58840730-cb600600-8634-11e9-8a29-21a8731f9357.png)

**Comment by ilko-k** [comment]
@wangqr sorry, I'm on Windows, and it pccurs on both x64-32 versions. I know that it is working when converting to UTF-8 BOM, it even works if we simply delete some lines of the srt file (even with no particular caracters). But unlike you, where the file seems to be still get open, I get an error msg and that's it. And sometimes, the error msg is different, saying that the directory is wrong or something. The most recent build I'm aware of is r8975 from line0.
![image](https://user-images.githubusercontent.com/5411848/58841458-3bd54a00-866a-11e9-8362-104d2f22f56e.png)

And somehting even more weird that I don't understand, in the build 8870, the full untouched file gets opened well, while the test file I've submitted earlier make aegisub displaying a prompt for choosing encoding.
![image](https://user-images.githubusercontent.com/5411848/58841708-683d9600-866b-11e9-8fff-eab2870e5f35.png)

[untouched_srt_file.zip](https://github.com/Aegisub/Aegisub/files/3249875/untouched_srt_file.zip)

**Comment by wangqr** [comment]
@ilko-k The error dialog is shown when the detected charset is incorrect, and the choosing dialog is shown when uchardet cannot detect the encoding.

The charset detection code can be found [here](https://github.com/Aegisub/Aegisub/blob/master/libaegisub/common/charset.cpp#L44-L45), it calls uchardet_data_end multiple times in the loop, which seems causing the problem. As I mentioned above, I reworte this part in f733297499f72ea11c166f6be23751a7b002c51c, but this is just a quick fix.

I made a binary build containing that commit at https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20190523.zip. It also uses the uchardet 0.0.6, which is a little bit newer than the original version used by Aegisub. It should be able to handle most charsets, including utf-8 w/ and w/o BOM.

**Comment by ilko-k** [comment]
@wangqr Yes it seems to work well, thank you very much ! Already compiled a setup for my needs : )

**Comment by wangqr** [comment]
@ilko-k The issue happens when Aegisub tries to auto load audio track from the dummy video, and is fixed in 8f40ca4. If you find further bugs, it would be better to open a separate issue to keep this issue on topic. Thanks for the report.

**Comment by ilko-k** [comment]
@wangqr alright, thank you again.

**Comment by wangqr** [comment]
@daT4v1s Oh I just saw your update. I reproduced the issue on Ubuntu 18.04, and confirmed that it can be solved by upgrading the wxGTK3 to 3.1.2, by following [this guide](https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries#toc2) which is linked from the [wxWidgets download page](https://www.wxwidgets.org/downloads/).

Aegisub and other applications depending on wxWidgets need to be rebuilt after upgrading wxWidgets.

![image](https://user-images.githubusercontent.com/8182182/59140873-bc998c00-8971-11e9-8e34-9bc725ccbfd5.png)

Additional fonts may be required to make it render correctly.
